# Generated by Django 4.1.7 on 2024-03-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customuser_kyc_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
