# Generated by Django 4.1.7 on 2024-04-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_investment_daily_return_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
    ]
