# Generated by Django 4.1.7 on 2024-04-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_investment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentsubscription',
            name='end_date',
        ),
    ]
