# Generated by Django 4.1.7 on 2024-04-03 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_investmentsubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsubscription',
            name='wallet',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.wallet'),
        ),
    ]
