# Generated by Django 4.1.7 on 2024-04-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_investmentsubscription_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentsubscription',
            name='wallet',
            field=models.ForeignKey(blank=True, default='Bitcoin', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.wallet'),
        ),
    ]
