# Generated by Django 4.1.7 on 2024-04-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet',
        ),
    ]
