# Generated by Django 4.1.7 on 2024-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
