# Generated by Django 4.1.7 on 2024-04-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_investmentsubscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
