# Generated by Django 4.1.7 on 2024-04-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_transaction_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
