# Generated by Django 4.1.7 on 2024-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-picture.png', null=True, upload_to='profile_pics'),
        ),
    ]
