# Generated by Django 5.0.6 on 2024-05-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='captcha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
