# Generated by Django 5.0.6 on 2024-05-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_customuser_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='captcha',
        ),
    ]
